"""education and featured

Revision ID: 4a5e2e104fc2
Revises: 4bb66b020f4f
Create Date: 2023-06-02 13:11:34.272907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5e2e104fc2'
down_revision = '4bb66b020f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('education')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
