"""headline and talks_about

Revision ID: 4bb66b020f4f
Revises: b7bf21c24ccd
Create Date: 2023-06-01 20:17:17.410677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb66b020f4f'
down_revision = 'b7bf21c24ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('talks_about', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('talks_about')
        batch_op.drop_column('headline')

    # ### end Alembic commands ###
